name: Run PyTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install python dependencies
        run: |
          poetry install
      - name: Test with pytest
        run: |
          poetry run pytest
